name: sdk/shopify-oxygen

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-shopify-oxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          # https://shopify.dev/docs/storefronts/headless/hydrogen/getting-started#requirements
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/shopify-oxygen-sdk'
          workspace_path: packages/sdk/shopify-oxygen
      - name: Install contract test service dependencies
        run: yarn workspace @launchdarkly/shopify-oxygen-contract-tests install --no-immutable
      - name: Build the test service
        run: yarn workspace @launchdarkly/shopify-oxygen-contract-tests build
      - name: Launch the test service in the background
        run: yarn workspace @launchdarkly/shopify-oxygen-contract-tests start &> /dev/null &
      - uses: launchdarkly/gh-actions/actions/contract-tests@68e9b2f165f60934308f18e4b75623c30b905c38
        with:
          test_service_port: 8000
          token: ${{ secrets.GITHUB_TOKEN }}
          # Based on run-test-harness.sh from the sdk package
          extra_params: '--url http://localhost:8000 --skip "streaming.*" --skip "evaluation.*" --skip "event.*" --skip "service.*" --stop-service-at-end'
